// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSettings } from "./AppSettings";

export interface AppConfig { id: string, name: string, version: string, description: string, identifier: string, settings: AppSettings, }