// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorMode } from "./ColorMode";
import type { Theme } from "./Theme";

export interface AppSettings { defaultLocale: string, supportedLocales: Array<string>, theme: string, themes: Array<Theme>, colorMode: ColorMode, }