// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataBinding } from "./DataBinding";
import type { GridPosition } from "./GridPosition";

export interface CanvasElement { id: string, componentId: string, gridPosition: GridPosition, classes: string, children: Array<string>, dataBinding: DataBinding | null, }