// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ComponentProp { propType: string, options: Array<string> | null, required: boolean, }