// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CrudResult<T> { data: T | null, list: Array<T>, count: number, success: boolean, message: string | null, }