// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ElementLayout { direction: string | null, mainAxis: string | null, crossAxis: string | null, mainAxisSize: string | null, spacing: number | null, colGap: number | null, rowGap: number | null, overflow: string | null, align: string | null, columns: number | null, }