// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EventSignature { name: string, description: string | null, payloadType: string | null, returnType: string | null, }
