// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridPosition } from "./GridPosition";
import type { ResponsiveClasses } from "./ResponsiveClasses";

export interface GridElement { id: string, componentId: string, classes: string | null, gridPosition: GridPosition, responsiveClasses: ResponsiveClasses | null, slot: string | null, }
