// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridArea } from "./GridArea";
import type { GridTrack } from "./GridTrack";
import type { ResponsiveBreakpoints } from "./ResponsiveBreakpoints";

export interface GridTemplate { id: string, columns: Array<GridTrack>, rows: Array<GridTrack>, gap: string, areas: Array<GridArea> | null, breakpoints: ResponsiveBreakpoints | null, }