// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GridPosition { column: number, row: number, colSpan: number, rowSpan: number, colStart: number | null, rowStart: number | null, }