// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GridDefaults { defaultColSpan: number, defaultRowSpan: number, minWidth: string | null, maxWidth: string | null, }