// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HandlerDef { handlerType: string | null, command: string | null, store: string | null, field: string | null, fnName: string | null, }