// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocaleMap } from "./LocaleMap";

export interface I18nConfig { locales: Record<string, LocaleMap>, }