// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTemplate } from "./GridTemplate";
import type { LayoutSlot } from "./LayoutSlot";

export interface Layout { id: string, name: string, slots: Record<string, LayoutSlot>, gridTemplate: GridTemplate | null, }