// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TailwindResponsiveClasses } from "./TailwindResponsiveClasses";

export interface LayoutSlot { componentId: string | null, height: string | null, width: string | null, dynamic: boolean, gridColumn: string | null, gridRow: string | null, gridArea: string | null, responsiveClasses: TailwindResponsiveClasses | null, }