// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandDef } from "./CommandDef";

export interface ModuleDef { id: string, name: string, commands: Array<CommandDef>, middleware: Array<string>, }