// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NamedGridArea { name: string, colStart: number | null, colEnd: number | null, rowStart: number | null, rowEnd: number | null, }