// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasElement } from "./CanvasElement";
import type { PageMeta } from "./PageMeta";
import type { PageSection } from "./PageSection";

export interface Page { id: string, name: string, route: string, layout: string | null, meta: PageMeta, sections: Record<string, PageSection>, canvasElements: Array<CanvasElement>, }