// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PaginatedResult<T> { items: Array<T>, hasMore: boolean, totalCount: number, }