// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageMeta } from "./PageMeta";
import type { RenderedSection } from "./RenderedSection";
import type { RenderedElement } from "./RenderedElement";

export interface RenderedPage { pageId: string, name: string, route: string, meta: PageMeta, layoutId: string | null, sections: Record<string, RenderedSection>, canvasElements: Array<RenderedElement>, resolvedBindings: Record<string, any>, }
