// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridPosition } from "./GridPosition";
import type { DataBinding } from "./DataBinding";

export interface RenderedElement { id: string, componentId: string, gridPosition: GridPosition, props: Record<string, any>, resolvedProps: any | null, classes: string, children: Array<string>, dataBinding: DataBinding | null, }
