// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ResponsiveClasses { sm: string | null, md: string | null, lg: string | null, xl: string | null, }