// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ResponsiveBreakpoints { mobileCols: number, smCols: number | null, mdCols: number | null, lgCols: number | null, xlCols: number | null, gap: string, smGap: string | null, mdGap: string | null, lgGap: string | null, xlGap: string | null, }