// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export interface Response<T> { status: Status, message: string, data: T | null, }