// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceCrud } from "./ServiceCrud";
import type { ServiceField } from "./ServiceField";

export interface ServiceDef { id: string, name: string, entity: string, provider: string, crud: ServiceCrud, fields: Array<ServiceField>, }