// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ServiceCrud { create: boolean, read: boolean, update: boolean, delete: boolean, query: boolean, }