// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridPosition } from "./GridPosition";
import type { TailwindResponsiveClasses } from "./TailwindResponsiveClasses";

export interface TailwindGridElement { id: string, componentId: string, classes: string | null, gridPosition: GridPosition, responsiveClasses: TailwindResponsiveClasses | null, slot: string | null, }