// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeColors } from "./ThemeColors";

export interface Theme { name: string, label: string, colors: ThemeColors, }