// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfig } from "./AppConfig";
import type { ComponentDef } from "./ComponentDef";
import type { I18nConfig } from "./I18nConfig";
import type { Layout } from "./Layout";
import type { ModuleDef } from "./ModuleDef";
import type { Page } from "./Page";
import type { ServiceDef } from "./ServiceDef";

export interface UiSchema { schemaVersion: string, app: AppConfig, pages: Array<Page>, layouts: Array<Layout>, components: Array<ComponentDef>, sharedComponents: Array<ComponentDef>, services: Array<ServiceDef>, modules: Array<ModuleDef>, i18N: I18nConfig, }