// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaValidationError } from "./SchemaValidationError";

export interface ValidationResult { valid: boolean, errors: Array<SchemaValidationError>, }