// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationError } from "./ValidationError";

export interface ValidationResult { valid: boolean, errors: Array<ValidationError>, }